### ISSUE TITLE
Asp.Net core sample connecting to message hub from Bluemix

### ISSUE THREAD

**Issue by goupadhy** [ibm-messaging/event-streams-samples#14]
Hi Team,
I know there is sample in Java and Node, Is there any asp.net core sample that will connect to message hub service in bluemix?

We have tried to explore with https://libraries.io/nuget/kafka-core and https://github.com/ah-/rdkafka-dotnet but unable to connect with it.

**Comment by edoardocomar** [comment]
Hi @goupadhy we have not tried any asp.net kafka library. 
The requirement to connect to IBM MessageHub Kafka in Bluemix is to support the SASL PLAIN authentication mechanism over an SSL connection. 
Of the two libraries you mention, the first is described by the author as a personal pet project.
The second one is based on `librdkafka` which supports the options we need **except on Windows, where SASL is not implemented**
Please see the options set in the node.js console sample that get passed to librdkafka.

AFAIK at the moment, on Windows the best option is to use the Java client.

**Comment by goupadhy** [comment]
Thanks for your response. We are trying to use asp.net core instead of node/java. We are trying to connect from Asp.Net Core application running on Bluemix not **windows machine.** Is there a way we can talk to message hub from asp.net core that you are aware of?

**Comment by edoardocomar** [comment]
Hi @goupadhy we have not looked at asp.net clients.

As https://github.com/ah-/rdkafka-dotnet is based on `librdkafka` that seems a candidate.
Please note 
1 - the librdkafka options required to connect , see the js example 
```
    var driver_options = {
        //'debug': 'all',
        'metadata.broker.list': opts.brokers,
        'security.protocol': 'sasl_ssl',
        'ssl.ca.location': opts.calocation,
        'sasl.mechanisms': 'PLAIN',
        'sasl.username': opts.username,
        'sasl.password': opts.password
    };
```
2 - At least on the Bluemix buildpack for node.js, librdkafka does not build with SASL enabled because of a missing development library. 
Our workaround, again illustrated by the `kafka-nodejs-console-sample` example was to deploy a prebuilt binary.

**Comment by mimaison** [comment]
We're not planning on adding a .Net sample at the moment. 

This .Net client should work with Event Streams: https://github.com/confluentinc/confluent-kafka-dotnet as it's based on librdkafka which we know works well
