### ISSUE TITLE
Issue while deploying to bluemix

### ISSUE THREAD

**Issue by AbhishekKaura25** [ibm-messaging/event-streams-samples#18]
I am trying to push the example code in bluemix but it is failing. Please find the sample below

-----> Downloaded app package (12K)

-----> IBM SDK for Node.js Buildpack v3.12-20170505-0656
       Based on Cloud Foundry Node.js Buildpack v1.5.24
-----> Creating runtime environment
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  6.10
       engines.npm (package.json):   unspecified (use default)
       Resolving node version 6.10 via 'node-version-resolver'
       Installing IBM SDK for Node.js (6.10.2) from cache
       Using default npm version: 3.10.10
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Checking and configuring service extensions before installing dependencies
-----> Building dependencies
       Installing node modules (package.json)
       > node-rdkafka@1.0.3 install /tmp/staged/app/node_modules/node-rdkafka
       > node-gyp rebuild
       make: Entering directory `/tmp/staged/app/node_modules/node-rdkafka/build'
       ACTION configuring librdkafka... deps/librdkafka/config.h
       checking for OS or distribution... ok (Ubuntu)
       checking for C compiler from CC env... failed
       checking for gcc (by command)... ok
       checking for C++ compiler from CXX env... failed
       checking for C++ compiler (g++)... ok
       checking executable ld... ok
       checking executable nm... ok
       checking executable strip... ok
       checking for pkgconfig (by command)... ok
       checking for install (by command)... ok
       checking for PIC (by compile)... ok
       checking for GNU-compatible linker options... ok
       checking for GNU linker-script ld flag... ok
       checking for __atomic_32 (by compile)... ok
       checking for __atomic_64 (by compile)... ok
       checking for socket (by compile)... ok
       parsing version '0x000905ff'... ok (0.9.5)
       checking for libpthread (by pkg-config)... failed
       checking for libpthread (by compile)... ok
       checking for zlib (by pkg-config)... ok
       checking for zlib (by compile)... ok
       checking for libcrypto (by pkg-config)... ok
       checking for libcrypto (by compile)... ok
       checking for liblz4 (by pkg-config)... failed
       checking for liblz4 (by compile)... failed (disable)
       checking for libssl (by pkg-config)... ok
       checking for libssl (by compile)... ok
       checking for libsasl2 (by pkg-config)... failed
       checking for libsasl2 (by compile)... failed (disable)
       checking for libsasl (by pkg-config)... failed
       checking for libsasl (by compile)... failed (disable)
       checking for regex (by compile)... ok
       checking for librt (by pkg-config)... failed
       checking for librt (by compile)... ok
       checking for strndup (by compile)... ok
       checking for nm (by env NM)... ok (cached)
       checking for python (by command)... ok
       Generated Makefile.config
       Generated config.h
       Configuration summary:
       prefix                   /usr/local
       ARCH                     x86_64
       CPU                      generic
       GEN_PKG_CONFIG           y
       ENABLE_DEVEL             n
       ENABLE_VALGRIND          n
       ENABLE_REFCNT_DEBUG      n
       ENABLE_SHAREDPTR_DEBUG   n
       ENABLE_LZ4_EXT           y
       ENABLE_SSL               y
       ENABLE_SASL              y
       MKL_APP_NAME             librdkafka
       MKL_DISTRO               Ubuntu
       LD                       ld
       NM                       nm
       OBJDUMP                  objdump
       LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
       CFLAGS
       MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
       CC                       gcc
       CXX                      g++
       STRIP                    strip
       CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
       PKG_CONFIG               pkg-config
       INSTALL                  install
       LDFLAG_LINKERSCRIPT      -Wl,--version-script=
       RDKAFKA_VERSION_STR      0.9.5
       MKL_APP_VERSION          0.9.5
       LIBS                     -lpthread -lz   -lz -lcrypto   -lcrypto -lssl -lcrypto   -lssl -lrt
       CXXFLAGS                 -Wno-non-virtual-dtor
       SYMDUMPER                $(NM) -D
       exec_prefix              /usr/local
       bindir                   /usr/local/bin
       sbindir                  /usr/local/sbin
       libexecdir               /usr/local/libexec
       datadir                  /usr/local/share
       sysconfdir               /usr/local/etc
       sharedstatedir           /usr/local/com
       localstatedir            /usr/local/var
       libdir                   /usr/local/lib
       includedir               /usr/local/include
       infodir                  /usr/local/info
       mandir                   /usr/local/man
       Generated config.cache
       Now type 'make' to build
       TOUCH Release/obj.target/deps/librdkafka_config.stamp
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_range_assignor.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdstring.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_op.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/lz4.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_transport.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/tinycthread.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdcrc32.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_partition.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_request.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_pattern.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_timer.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_conf.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_offset.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_event.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/snappy.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/xxhash.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdaddr.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_feature.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_roundrobin_assignor.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_queue.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_metadata_cache.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_assignor.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_broker.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_metadata.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdrand.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdlist.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdregex.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_subscription.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdgz.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_topic.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdports.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdavl.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/lz4hc.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msg.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/lz4frame.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdlog.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_cgrp.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_buf.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/regexp.o
       CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl.o
       ../deps/librdkafka/src/rdkafka_sasl.c: In function ‘rd_kafka_sasl_io_event’:
       ../deps/librdkafka/src/rdkafka_sasl.c:129:23: error: ‘rd_kafka_transport_t’ has no member named ‘rktrans_sasl’
       return rktrans->rktrans_sasl.recv(rktrans,
       ^
       In file included from /usr/include/string.h:635:0,
       from ../deps/librdkafka/src/rd.h:45,
       from ../deps/librdkafka/src/rdkafka_int.h:44,
       from ../deps/librdkafka/src/rdkafka_sasl.c:29:
       ../deps/librdkafka/src/rdkafka_sasl.c: In function ‘rd_kafka_sasl_client_new’:
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
       ^
       In file included from ../deps/librdkafka/src/rd.h:68:0,
       from ../deps/librdkafka/src/rdkafka_int.h:44,
       from ../deps/librdkafka/src/rdkafka_sasl.c:29:
       ../deps/librdkafka/src/rdkafka_sasl.c:168:40: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       rk->rk_conf.sasl.mechanisms,
       ^
       ../deps/librdkafka/src/rdposix.h:83:36: note: in definition of macro ‘rd_snprintf’
       #define rd_snprintf(...)  snprintf(__VA_ARGS__)
       ^
       In file included from ../deps/librdkafka/src/rdkafka_sasl.c:29:0:
       ../deps/librdkafka/src/rdkafka_sasl.c:181:31: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       rk->rk_conf.sasl.service_name, hostname,
       ^
       ../deps/librdkafka/src/rdkafka_int.h:367:43: note: in definition of macro ‘rd_rkb_log’
       level, fac, __VA_ARGS__);                                                            ^
       ../deps/librdkafka/src/rdkafka_sasl.c:178:9: note: in expansion of macro ‘rd_rkb_dbg’
       rd_rkb_dbg(rkb, SECURITY, "SASL",
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:182:31: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       rk->rk_conf.sasl.mechanisms);
       ^
       ../deps/librdkafka/src/rdkafka_int.h:367:43: note: in definition of macro ‘rd_rkb_log’
       level, fac, __VA_ARGS__);                                                            ^
       ../deps/librdkafka/src/rdkafka_sasl.c:178:9: note: in expansion of macro ‘rd_rkb_dbg’
       rd_rkb_dbg(rkb, SECURITY, "SASL",
       ^
       In file included from /usr/include/string.h:635:0,
       from ../deps/librdkafka/src/rd.h:45,
       from ../deps/librdkafka/src/rdkafka_int.h:44,
       from ../deps/librdkafka/src/rdkafka_sasl.c:29:
       ../deps/librdkafka/src/rdkafka_sasl.c: In function ‘rd_kafka_sasl_conf_validate’:
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c:231:24: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’
       if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
       ^
       ../deps/librdkafka/src/rdkafka_sasl.c: In function ‘rd_kafka_sasl_io_event’:
       ../deps/librdkafka/src/rdkafka_sasl.c:135:1: warning: control reaches end of non-void function [-Wreturn-type]
       }
       ^
       make: *** [Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl.o] Error 1
       make: Leaving directory `/tmp/staged/app/node_modules/node-rdkafka/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
       gyp ERR! System Linux 4.4.0-45-generic
       gyp ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/staged/app/node_modules/node-rdkafka
       gyp ERR! node -v v6.10.2
       gyp ERR! node-gyp -v v3.4.0
       gyp ERR! not ok
       message-hub-nodejs-console-sample@3.0.0 /tmp/staged/app
       └─┬ message-hub-rest@1.2.0
       └── q@1.5.0
       npm ERR! Linux 4.4.0-45-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! node v6.10.2
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! node-rdkafka@1.0.3 install: `node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the node-rdkafka@1.0.3 install script 'node-gyp rebuild'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the node-rdkafka package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-gyp rebuild
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs node-rdkafka
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls node-rdkafka
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/npm-debug.log
-----> Build failed
       Check our support community to get help on common issues:
       http://ibm.biz/bluemixcommunitysupport
       If you need additional help and your subscription includes support, submit a ticket so we can help:
       http://ibm.biz/bluemixsupport
Staging failed: Buildpack compilation step failed

**Comment by edoardocomar** [comment]
looks like the Bluemix CF environment you are pushing to is missing `libsasl2-dev`

which is unexpected ... what Bluemix environment is that you're pushing to ?

you may try to checkout an older version 
where we had to package prebuilt node-rdkafka binaries
https://github.com/ibm-messaging/message-hub-samples/tree/849a42d4d77e77e48a5c2934eefa93af7a832a38

**Comment by AbhishekKaura25** [comment]
@edoardocomar  Thanks !! I will try this option

**Comment by edoardocomar** [comment]
@AbhishekKaura25 in which bluemix env did you encounter the issue

**Comment by hungtv55** [comment]
I'm using dedicated Bluemix and it is failing to build node-rdkafka with SASL
```
#include <sasl/sasl.h>
       compilation terminated.
       ../deps/librdkafka/src/rdkafka_sasl_cyrus.c:39:23: fatal error: sasl/sasl.h: No such file or directory
       ^
       make: *** [Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_cyrus.o] Error 1
       make: Leaving directory `/tmp/app/node_modules/node-rdkafka/build'````
Perhaps Bluemix dedicated still miss `libsasl2-dev`

**Comment by mimaison** [comment]
@hungtv55 which bluemix environment are you using ?

**Comment by hungtv55** [comment]
@mimaison : I'm sorry for late reply. Here is info of our dedicated Bluemix version:
```
   "name": "Bluemix",
   "build": "235026",
   "support": "http://ibm.com",
```
Btw, we found a solution for this issue by using multiple buildpacks (apt + nodejs buildpack). In `Apt` file  of apt buildpack, you can add `libsasl2-dev` to install this library in Bluemix container.

**Comment by mimaison** [comment]
All dedicated environments have been updated. This should not be an issue anymore
