### ISSUE TITLE
Update samples to support Kubernetes

### ISSUE THREAD

**Issue by rvennam** [ibm-messaging/event-streams-samples#23]
1) Change "Bluemix" references to IBM Cloud.
2) Existing checks to see if app is running in Bluemix should be changed to CloudFoundry
3) Add code to read credentials passed in as Kube secrets -> env variable. 

I'm happy to work with a developer on this or send a PR.

**Comment by mimaison** [comment]
Thanks Ram for noticing these issues. Reach out to me internally and we can go over what's required to do.

**Comment by mimaison** [comment]
I believe all these issues have been addressed, closing
