### ISSUE TITLE
ModuleNotFoundError: No module named 'confluent_kafka'

### ISSUE THREAD

**Issue by doyoungim999** [ibm-messaging/event-streams-samples#44]
How can i fix the issue? 
When i run python3 app.py , I got the error:
ModuleNotFoundError: No module named 'confluent_kafka'

**Comment by mimaison** [comment]
This indicates you have not installed the `confluent_kafka` library in your python3 environment.

You may need to adapt the instructions a bit for your environment and instead run `pip3 install -r requirements.txt` to install the dependencies.

**Comment by doyoungim999** [comment]
It works. 
Thank you
