### ISSUE TITLE
Does the event-stream support the schema-registry in IBM public cloud?

### ISSUE THREAD

**Issue by bjlvfei** [ibm-messaging/event-streams-samples#54]
Hi Team,

I have checked the event-stream document in IBM public cloud where not found scheme-registry. Does it support scheme-registry? 

Thanks!
Levi

**Comment by mimaison** [comment]
The Enterprise plan now comes with a Schema Registry, see https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ES_schema_registry
