### ISSUE TITLE
Connectors not listed

### ISSUE THREAD

**Issue by balajikadambi** [ibm-messaging/event-streams-samples#59]
Hi,

We tried deploying the connectors on Kafka connect. We followed the instructions given in the GitHub README.
The connector is not getting listed when we run the below commands:

```
$ curl http://localhost:8083
{"version":"2.5.0","commit":"66563e712b0b9f84","kafka_cluster_id":"jYm3VyL3RgS92suAs1GRXg"}
```

```
$ curl http://localhost:8083/connectors
[]
```
Could you help resolve the issue.

Thanks,
Balaji

**Comment by mimaison** [comment]
Have you seen https://github.com/ibm-messaging/kafka-connect-ibmcos-sink/issues/8#issuecomment-632613777. I wonder if you have the same issue.

**Comment by balajikadambi** [comment]
I had not started the connector. After starting the connector, it is getting listed.
