### ISSUE TITLE
k8s lab kafka-java-console-schema-sample fails because image is not on dockerhub

### ISSUE THREAD

**Issue by csantanapr** [ibm-messaging/event-streams-samples#65]
Try lab Kubernetes lab https://github.com/ibm-messaging/event-streams-samples/blob/master/kafka-java-console-schema-sample/docs/Kubernetes_Service.md

```
failed to pull and unpack image "docker.io/ibmcom/kafka-java-console-schema-sample:latest"
```

**Comment by mimaison** [comment]
I believe this issue has been fixed, I'm able to pull this image right now
