### ISSUE TITLE
[Question] Out of curiosity, is `ssl.ca.location` now necessary to connect with Event Streams?

### ISSUE THREAD

**Issue by ericqqqqq** [ibm-messaging/event-streams-samples#67]
I used `kafka-node`(now does not work) to connect with IBM Event Streams. The full configuration was
```
{
      kafkaHost: kafka_brokers_sasl,
      sslOptions: { rejectUnauthorized: false },
      sasl: {
        mechanism: "plain",
        username: user,
        password: password
      }
};
```

However, when looking at the nodejs sample that uses `node-rdkafka`, we need to pass in an extra value: `ssl.ca.location` comparing to `kafka-node`. 

Saw [this answer](https://github.com/ibm-messaging/event-streams-samples/issues/43) and saw that `ssl.ca.location` is needed to _enable the Kafka client to verify the broker keys_.

Was cert unnecessary for Event Streams before then becomes necessary recently?

Out of curiosity, I also wondering why `kafka-node` stopped working with Event Streams.

Thanks

**Comment by mimaison** [comment]
Our recommended Node.js client is [node-rdkafka](https://github.com/Blizzard/node-rdkafka). We don't test explicitly with kafka-node.
That said, we have some users running kafka-node and it used to work. I'm also not aware of a recent change that could have broken it. Can you share some logs to help us understand what's wrong with kafka-node?

To go back to your question, yes `ssl.ca.location` is required with node-rdkafka and always have been. We also don't recommend disabling any TLS validations (`rejectUnauthorized: false`) as these can allow a range of attacks that can compromise the security of your data.

**Comment by ericqqqqq** [comment]
Hi @mimaison . Thanks for the reply.

I was asking about `kafka-node`, as I remembered that `kafka-node` was recommended by IBM Event Stream before(if I recall it right). These days, I found the `kafka-node` stopped working and I found this [documentation](https://github.com/ibm-cloud-docs/EventStreams/blame/master/eventstreams141.md#L115-L127), but not sure why these unsupported libraries section is commented out.

With that said, when I have configuration:
```
{
      kafkaHost: kafka_brokers_sasl,
      sslOptions: { rejectUnauthorized: false },
      sasl: {
        mechanism: "plain",
        username: user,
        password: password
      }
};
```

I get the errors:
```
{ TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/path/to/project/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.timeoutId._createTimeout [as _onTimeout] (/path/to/project/node_modules/kafka-node/lib/kafkaClient.js:1012:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) message: 'Request timed out after 30000ms' }
```

However, I found a workaround [here](https://github.com/SOHU-Co/kafka-node/issues/1188). And what we discussed there is  the error we are facing. If I pass `servername` under `sslOptions`
```
{
      kafkaHost: kafka_brokers_sasl,
      sslOptions: {
           rejectUnauthorized: false,
           servername: one of the kafka broker server name
      },
      sasl: {
        mechanism: "plain",
        username: user,
        password: password
      }
};
```
It works. However, I need luck to have leader broker passed in. Therefore, I suppose it is not a workaround for production environment.

Any ideas what is going wrong with the `kafka-node`?

**Comment by mimaison** [comment]
I guess you were previously using the Classic plan. This plan was retired earlier this year.

All our current plans (since early 2019) require Kafka clients to use SNI (Server Name Indication). In `kafka-node` this is enabled via the `servername` setting. This is not a workaround but the correct configuration. The Classic plan did not require SNI.

**Comment by ericqqqqq** [comment]
Thanks @mimaison 

You are right, I was using the Classic plan. I am trying to migrate the project to use the standard plan. I thought using `node-rdkafka` is the proper way until you mentioned that adding servername is the correct configuration instead of a `workaround`.

However, I have a concern, does the `leader broker` change? If I am not providing the leader broker, I would get `NotLeaderForPartition`. If that is the case, I will need to carefully handle that situation.

Thanks

**Comment by mimaison** [comment]
I don't know kafka-node very well, but yes the fact that you can only provide a single servername is likely to be problematic. I see there's an open PR to address this: https://github.com/SOHU-Co/kafka-node/pull/1375.

Our recommendation is still to use node-rdkafka. This is a client we continuously test and know works well.

**Comment by ericqqqqq** [comment]
Thank you very much, I think I will implement another API with node-rdkafka for my project.

**Comment by mimaison** [comment]
If I've answered your questions, can we close this ticket?

**Comment by ericqqqqq** [comment]
Yes.
