### ISSUE TITLE
Use in Spark as a Service on Bluemix

### ISSUE THREAD

**Issue by rosswlewis** [ibm-messaging/event-streams-samples#7]
Is it possible to use these jars on Spark as a service on Bluemix?  I'm getting an error dump when I try to import any of them:

//%Addjar -f https://github.com/ibm-messaging/message-hub-samples/raw/master/java/message-hub-login-library/messagehub.login-1.0.0.jar
//%Addjar -f https://github.com/ibm-messaging/message-hub-samples/raw/master/java/message-hub-kafka-ssl/lib-message-hub/messagehub.login-1.0.0.jar
//%Addjar -f https://github.com/ibm-messaging/message-hub-samples/raw/master/java/message-hub-liberty-sample/lib-message-hub/messagehub.login-1.0.0.jar

import com.ibm.cds.spark.samples.config.MessageHubConfig

**Comment by mimaison** [comment]
Closing this issue as we don't support this custom login module anymore. Since Kafka 0.10, clients can connect out of the box and don't require this extra module
