### ISSUE TITLE
java sample doesn't build with gradle 7 which is latest version as of Apr 09, 2021

### ISSUE THREAD

**Issue by brunnjf** [ibm-messaging/event-streams-samples#74]
Builds with 6.8.3, but the Java sample gradle file uses the compile configuration which is removed from Gradle 7. Note that the 6.8.3 install will give this message:

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

As of gradle 7.0, you simply get:

> * What went wrong:
> A problem occurred evaluating root project 'kafka-java-console-sample'.
> > Could not find method compile() for arguments [org.apache.kafka:kafka-clients:2.4.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

There isn't a brew target for gradle 6.8.3, making it more difficult to install the older version needed to build the sample now.

**Comment by edoardocomar** [comment]
fixed by https://github.com/ibm-messaging/event-streams-samples/pull/75

**Comment by mimaison** [comment]
Thanks for the report. We pushed a fix.
